version: '3.9'

services:
  app:
    build: ./apps/app
    container_name: ecollectivites-app
    command: yarn dev
    depends_on:
      - api
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - API_BASE_URL=http://localhost:8000
    volumes:
      - ./apps/app:/app

  api:
    build: ./apps/api
    container_name: ecollectivites-api
    command: yarn dev
    ports:
      - 8000:8000
    env_file:
      - ./apps/api/.env
    environment:
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/ecollectivites?schema=public
    volumes:
      - ./apps/api/src:/app/src
      - uploads:/app/uploads
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    container_name: ecollectivites-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecollectivites
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
  uploads:
