version: '3.9'
services:
  app:
    build: .
    command: npm run dev
    ports:
      - '8000:3000'
    volumes:
      - ./src:/app/src
      - ./public/uploads:/app/public/uploads
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:admin@postgres:5432/prisma?schema=public
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecollectivites
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
