version: '3.9'
services:
  app:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      - PRISMA_DATABASE_URL=postgresql://postgres:admin@postgres:5432/prisma?schema=public
    depends_on:
      - postgres
  
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecollectivites
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: